// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    MyComponent: typeof import('./src/components/MyComponent.vue')['default']
    TheImage: typeof import('./src/components/TheImage.vue')['default']
    TheLogo: typeof import('./src/components/TheLogo.vue')['default']
    TheNav: typeof import('./src/components/TheNav.vue')['default']
  }
}

export { }
